### PR TITLE
Build dev

### PR DESCRIPTION
**Pull request by martijnberger**
Hi Ryan,

Here is a less offensive subset of my changes. 
I am still not 100% happy but at least your branch is much closer to what I like.

### CODE REVIEW

**Comment by rsgalloway** [comment]
Hey Martijn, thanks for this. Which parts are you unhappy about? FWIW, this build-dev branch is still a work-in-progress. 

Also, it looks like we might be missing a signed CLA from you guys. Is that something you can get to us before we merge this in? If this work is on behalf of Blender, please use the corporate CLA agreement on this page:

http://code.google.com/p/alembic/wiki/Downloads?tm=2

**Comment by martijnberger** [comment]
Hi Ryan,
I have made some (not all tests) working on my master branch. Ideally I want to make all non HDF5 specific tests work and I  do some more fix-ups and test building with and without options to make sure it is all solid. I also want to get rid of static Windows buildfiles for ancient (and obsolete ??) dependencies. 
I will sign the individual CLA tomorrow as I am not employed or compensated by the Blender Foundation or Institute but just a volunteer. I hope that also works.

**Comment by rsgalloway** [comment]
I believe there is going to be an effort to remove the HDF5 code from the tests, which seems like the right answer. Getting rid of obsolete dependencies is always a good thing. Once your CLA is approved we'll be able to merge this in.

**Comment by martijnberger** [comment]
Hi Ryan,

I signed the CLA and mailed it.  I also modified the tests so both backends are tested and tests work with and without HDF5.

**Pull request merged**
